name: flutter_plugin_elui_example
description: Demonstrates how to use the flutter_plugin_elui plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_plugin_elui:
    path: ../

flutter:
  uses-material-design: true
